import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        localStorage: 'readonly',
        FormData: 'readonly',
        fetch: 'readonly',
        Image: 'readonly',
        marked: 'readonly',
        jsyaml: 'readonly',
        DOMPurify: 'readonly',
        firebase: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        history: 'readonly',
        URL: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        crypto: 'readonly',
        matchMedia: 'readonly',
      },
    },
    rules: {
      indent: ['error', 2],
      'linebreak-style': ['error', 'unix'],
      quotes: ['error', 'single'],
      semi: ['error', 'always'],
      'no-unused-vars': 'warn',
      'no-console': 'off',
      'no-empty': 'warn',
    },
  },
];
